### ISSUE TITLE
Device Question

### ISSUE THREAD

**Issue by emi-dm** [SauravMaheshkar/samv2#3]
Is possible to use VideoPredictor in a device without GPU installed?

**Comment by SauravMaheshkar** [comment]
I haven't tested that yet, Let me get back to you.

**Comment by emi-dm** [comment]
I'm test the library with the notebook of official repo of SAM2 and it doesn't work! The model is loaded properly on the CPU 
![imagen](https://github.com/user-attachments/assets/84de594b-202f-45f4-876c-c0c134a1ec34)

But when you are going to init the state, it doesn't work
![imagen](https://github.com/user-attachments/assets/acd4e625-8162-475f-9685-ff498800eccf)

**Comment by SauravMaheshkar** [comment]
Could you try the code in https://github.com/SauravMaheshkar/samv2/blob/af7e893259b48992be4dd9793aab3fd68803952f/tests/test_video_predictor.py

https://github.com/SauravMaheshkar/samv2/blob/af7e893259b48992be4dd9793aab3fd68803952f/tests/test_video_predictor.py#L11-L27

**Comment by cocomoff** [comment]
Thank you for your great work to run SAM2 on CPU device. I also tried this issue and found that the model load is completed (by device "CPU").

After trying `build_sam2_video_predictor`, I faced the following error message from sam2. This could be related to the original issue https://github.com/facebookresearch/segment-anything-2/issues/25

Do you have any idea to resolve this for SAMV2? (or, have you already resolved?)

```
ImportError: cannot import name '_C' from 'sam2' (/<My Path>/.venv/lib/python3.12/site-packages/sam2/__init__.py)
```

**Comment by SauravMaheshkar** [comment]
@cocomoff Can you share your script ? I've got a test that runs successfully for one click on the CPU here:

https://github.com/SauravMaheshkar/samv2/blob/af7e893259b48992be4dd9793aab3fd68803952f/tests/test_video_predictor.py#L11-L27

**Comment by SauravMaheshkar** [comment]
@cocomoff thanks for sharing your environment. Can you download the latest package from Github and then try the script again? (I haven't pushed a new release to pypi because I want to test more) 

```bash
rye add samv2 --git https://github.com/SauravMaheshkar/samv2.git
```

I mostly run python 3.10.3 locally, and the CI tests for versions 3.8-3.11.

**Comment by cocomoff** [comment]
@SauravMaheshkar Thank you for sharing your versions and the installation method with `--git` option. It works as we expected :) Maybe, my `rye add` did not work well (to fetch the latest version).

JFYI: I encountered another issue of using `.cuda()` inside `SAM2Base`, which I manually fixed in my local environment. I just share this issue for you.

Here, `.cuda()` may cause the error like `AssertionError: Torch not compiled with CUDA enabled` if we use SAM2 only with CPU.

https://github.com/SauravMaheshkar/samv2/blob/main/sam2/modeling/sam2_base.py#L569-L572

Again, thanks for your great fork.

**Comment by SauravMaheshkar** [comment]
Glad to know, it worked out. I'm patching all the CUDA stuff in https://github.com/SauravMaheshkar/samv2/tree/saurav/make-gpu-optional

**Comment by SauravMaheshkar** [comment]
> I'm test the library with the notebook of official repo of SAM2 and it doesn't work! The model is loaded properly on the CPU ![imagen](https://private-user-images.githubusercontent.com/140513018/354349112-84de594b-202f-45f4-876c-c0c134a1ec34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTYxNjgsIm5iZiI6MTcyMjU5NTg2OCwicGF0aCI6Ii8xNDA1MTMwMTgvMzU0MzQ5MTEyLTg0ZGU1OTRiLTIwMmYtNDVmNC04NzZjLWMwYzEzNGExZWMzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxMDUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmRmYjk5ZWNkNzJiMjI0ZDNiYmMxMGRjYjEzOTZmOTlmYjc5NzJhZTdkYmVjMjMwYjdiMjQ3ODRjNjg2NjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cq3bD-D0oOAozzdhQiEh18tGeCLVNlAIvXThaBR2NIQ)
> 
> But when you are going to init the state, it doesn't work ![imagen](https://private-user-images.githubusercontent.com/140513018/354349270-acd4e625-8162-475f-9685-ff498800eccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTYxNjgsIm5iZiI6MTcyMjU5NTg2OCwicGF0aCI6Ii8xNDA1MTMwMTgvMzU0MzQ5MjcwLWFjZDRlNjI1LTgxNjItNDc1Zi05Njg1LWZmNDk4ODAwZWNjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxMDUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjI5NmI5OTJiNDc4MjQ0MGFjYjE3NzA1NmVlNzc5NDRmODkxMGEwYTc5NDkzZmNmYzlkYThjYzc2NWRjNDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y8w_4Th7e6Cr79ifxGMQS5ZaO-xiYnSAP7mK9L6SFC8)

@emi-dm where you able to get it working with the latest changes in https://github.com/SauravMaheshkar/samv2/tree/saurav/make-gpu-optional

**Comment by SauravMaheshkar** [comment]
@emi-dm I'm going to close this issue for now, I've tested that the model works for video prediction on the CPU in https://github.com/SauravMaheshkar/samv2/blob/main/tests/test_video_inference.py.

I've also added example notebooks, feel free to reopen this issue if you have questions or open another one.
